language: node_js
node_js:
- '8'
env:
  global:
  - DEPLOY_REPOSITORY="git@github.com:konnectors/amazon.git"
  - secure: quk38q8jOC2ly8RDzrHKw5z7H5C1fe0dDTaGWLwjZlyl01+1gBZTkWXE/EMV8/Oj7VG8HxEmHf/gZowKHcM6xEcA5Yj372wYUOyR5nJoOz2M7HtIcIJ7ApOZxyKVB/L6+f2e21fEPlZdcRMHNgCMtIi3DKPaH//KHImqIBhUY3KNYAhGQPrO+dl9DXbW4Fki5GzWpFCeBGvkgoKL9gLnXnrlBDf5kbJlN/mvgbJ3savFaJodeGowXrlCdS8SmJmsiuh1OIkO1gQEzwsoHDHO22GHKxHREi+wqTrw/dRxNXg9r2zB0mbbbxisOPi6r4ScuPYGAVF4Ci0AnZPOdrS3w0z0KDJkfeNEUdw6g6u8KqHoP1/vz4AP6+UCbMCE8C45PKlQ7EF6GFT5rnyKGB/SguHV93yrXIm45V+4SqZxYgy2HvzzxMU1BNvTnwPaMH2jypwRPHqboMGMt/aLyyYl+35rbAz1X2w77eJnexYH4MBqJJB2UkO6psqARUN+rAz4X5Xqf6bNZerMsNOdJ11XQakjAhdtdqDlmY9oAXUaZbMiDgLS2I8G17bH+Pq3mgTxIA0asd/5QqPpoPXlAuEGbniwNV+LP5pzIiGR60lONcQmW0DYZVoJycmn02PAZak/bLq2LrCSKvTcZq6hQVM1Ue+aWPbV0ASuMPRD5oLiHc8=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- echo 'Linting' && echo -en 'travis_fold:start:lint\\r'
- yarn lint
- echo -en 'travis_fold:end:lint\\r'
- echo 'Building' && echo -en 'travis_fold:start:build\\r'
- yarn build
- echo -en 'travis_fold:end:build\\r'
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_81655c776d09_key -iv $encrypted_81655c776d09_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
