language: node_js
node_js:
- '16.18.1'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=amazon)
  - secure: OzkmHah+atO2OMHF0dA0/LOIIkEMiGzRVK6UpH8a3JV1LUDizzahP5jwfnwedES2CK258KVO75TIhaSOHIOWe0Aw1bl9o3fxxCuEUn+luD2W+y8a6m3LiVCw4FlrU6SoOvURE62mLe7DKvQCBPjtMMP4wZuEvUhEujCyplIAXMcDNMo2w5tlA6OeWnieljdIxErP62uEyRCaUHI7ojRc9RKViv2oGfpqGOTmz+5YdnhGi8do/kjmrgdpOWESzC16athYNH1uMzGWdAzsttT/Wkr4xwz7D8b3nD1UyB1g2DuLtxQke0Fyp0gXz2UxXGnbaGjNNK1GfpSjfoMTHkjAG+aBP742vutYs5KxCudbkVNH1wNssB7hktLydWbsUYyyFHRr7EoZ+eTOGO77t+BD5I0JHzHueiGVDj69/MJ8mo8NHEroPpGfJr4ZsdC4cCinT7Er/X5F6lGY612lZbKAWest0XK7P9eiz2+pNI4VOrZXfUlDQtNj5os2OGIouIBKpvu7A6SiyfTN6c6O3+LlqQo/cHRyRmmtdThy8lLpWSSOgetRnp0FhdKGySkPRRQvCwxErtOKaHSIanvG6IJq4Fw6KE9JhCHiQECt0Ux7T6WMmqmX1UWFjeOMmFsyLYt1n1OGjp4uLY/fEtx7Rs41CDfQJs1vKPG+AaQSLcZ2yLc=
  # MATTERMOST_HOOK_URL
  - secure: HDBSJxHDe36mE8+Na9TnK3OjgUl/HFfjDWLtCnEVxDjUAkftNYkbIkxiMRY5IgFOZV21O5scN62eUTy+DGeyiVys9eJtlYz/h8kYUq/8GD5fkXdSwLrVwPjqelW1v2jj+WJqq5CnMW7hMNYtNuwPDMhePgR/Ly2WblwXhgrhpIiSiU9u7Uz94UA2EK722tKjFxMMHFh6YzKc4+tMicaPhht6L72aIFmym3wbKho/8XOo0XysVA9J454qgjNnz5bDPeYQmRqRc9WRna5c6uNCmidVy/FaTLiu1/d2EgFYAdK7oZ/pIukIYY4Kyc/wMMcLjsp2UMGrHOk+TZTWMaOP2Wu3R8pN62umLnAQsx/idhVrAE5CCNxk/EFaj2gOoWITRvrpOh2Des3MDK8Vy7s6Cp0SYU+sa4cWZCQg0BcLXB+KwmujMKU0r7JVOrEJdjJLdnvDznmWbe+Hmk0N9GMbMfayvDmFYZOq8fPa7jKg+yZK9GmCSB5V16zELT0BZMVGA5gLNdWjDjudiWsjTsxaV08lojVktpqwveVNgpsEyWLozcCOvD08xAmxJEsEM18P89xD09Tuc3z837OYXJ9l0VuufrpsRX+HT2nnIjho8Pw7Cy12h/gOeX6qc1ZADuSnRyCtob3gTSbrylag1h1UBzAAbhmu2Ivz+rMYeTWUAnY=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
